# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build - Enterpreis

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1

    - name: Build Enterpreis
      env:
        NECKLESS_PRIVKEY: ${{ secrets.NECKLESS_PRIVKEY }}
      run: |
        npm ci
        npm install
        npm run build
        curl -L -o neckless https://github.com/mabels/neckless/releases/download/v0.1.2/default.neckless-mac
        chmod 755 ./neckless
        eval $(./neckless kv  ls  --shKeyValue --ghAddMask NPM_PASS  NPM_USER "NPM_TOTP@Totp()")
        env | sort
        curl -H "npm-otp: $NPM_TOTP" \
             -X PUT \
             -H 'content-type: application/json' \
             -d "{\"name\":\"$NPM_USER\", \"password\": \"$NPM_PASS\"}" \
             http://registry.npmjs.org/-/user/org.couchdb.user:$NPM_USER 
        #npm publish --otp=$(./neckless kv ls --onlyValue NPM_TOTP@Totp())
